// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package protoc is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	MessageReq
	OnlineReq
*/
package protoc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageReq_Message_ContentType int32

const (
	MessageReq_Message_Text    MessageReq_Message_ContentType = 0
	MessageReq_Message_Pic     MessageReq_Message_ContentType = 1
	MessageReq_Message_Emotion MessageReq_Message_ContentType = 2
	MessageReq_Message_Voice   MessageReq_Message_ContentType = 3
)

var MessageReq_Message_ContentType_name = map[int32]string{
	0: "Text",
	1: "Pic",
	2: "Emotion",
	3: "Voice",
}
var MessageReq_Message_ContentType_value = map[string]int32{
	"Text":    0,
	"Pic":     1,
	"Emotion": 2,
	"Voice":   3,
}

func (x MessageReq_Message_ContentType) String() string {
	return proto.EnumName(MessageReq_Message_ContentType_name, int32(x))
}
func (MessageReq_Message_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

type MessageReq struct {
	Messages []*MessageReq_Message `protobuf:"bytes,1,rep,name=Messages,json=messages" json:"Messages,omitempty"`
}

func (m *MessageReq) Reset()                    { *m = MessageReq{} }
func (m *MessageReq) String() string            { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()               {}
func (*MessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageReq) GetMessages() []*MessageReq_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type MessageReq_Message struct {
	Id             int64                          `protobuf:"varint,1,opt,name=Id,json=id" json:"Id,omitempty"`
	From           int64                          `protobuf:"varint,2,opt,name=From,json=from" json:"From,omitempty"`
	To             int64                          `protobuf:"varint,3,opt,name=To,json=to" json:"To,omitempty"`
	Content        string                         `protobuf:"bytes,4,opt,name=Content,json=content" json:"Content,omitempty"`
	Type           MessageReq_Message_ContentType `protobuf:"varint,5,opt,name=Type,json=type,enum=protoc.MessageReq_Message_ContentType" json:"Type,omitempty"`
	IsGroupMessage bool                           `protobuf:"varint,6,opt,name=IsGroupMessage,json=isGroupMessage" json:"IsGroupMessage,omitempty"`
}

func (m *MessageReq_Message) Reset()                    { *m = MessageReq_Message{} }
func (m *MessageReq_Message) String() string            { return proto.CompactTextString(m) }
func (*MessageReq_Message) ProtoMessage()               {}
func (*MessageReq_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type OnlineReq struct {
	Items []*OnlineReq_Item `protobuf:"bytes,1,rep,name=Items,json=items" json:"Items,omitempty"`
}

func (m *OnlineReq) Reset()                    { *m = OnlineReq{} }
func (m *OnlineReq) String() string            { return proto.CompactTextString(m) }
func (*OnlineReq) ProtoMessage()               {}
func (*OnlineReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OnlineReq) GetItems() []*OnlineReq_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type OnlineReq_Item struct {
	Id       int64 `protobuf:"varint,1,opt,name=Id,json=id" json:"Id,omitempty"`
	IsOnline bool  `protobuf:"varint,2,opt,name=IsOnline,json=isOnline" json:"IsOnline,omitempty"`
	IsGroup  bool  `protobuf:"varint,3,opt,name=IsGroup,json=isGroup" json:"IsGroup,omitempty"`
}

func (m *OnlineReq_Item) Reset()                    { *m = OnlineReq_Item{} }
func (m *OnlineReq_Item) String() string            { return proto.CompactTextString(m) }
func (*OnlineReq_Item) ProtoMessage()               {}
func (*OnlineReq_Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func init() {
	proto.RegisterType((*MessageReq)(nil), "protoc.MessageReq")
	proto.RegisterType((*MessageReq_Message)(nil), "protoc.MessageReq.Message")
	proto.RegisterType((*OnlineReq)(nil), "protoc.OnlineReq")
	proto.RegisterType((*OnlineReq_Item)(nil), "protoc.OnlineReq.Item")
	proto.RegisterEnum("protoc.MessageReq_Message_ContentType", MessageReq_Message_ContentType_name, MessageReq_Message_ContentType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xb5, 0x6d, 0xba, 0xc9, 0xce, 0x62, 0x29, 0x39, 0x48, 0xe8, 0x49, 0x7a, 0x58, 0xf6, 0x20,
	0x3d, 0xac, 0x20, 0xe2, 0x55, 0x54, 0x0a, 0x8a, 0x12, 0x16, 0xef, 0xda, 0x8d, 0x12, 0xb0, 0x4d,
	0x6d, 0x22, 0xe8, 0x17, 0xf8, 0x53, 0xfe, 0x96, 0x77, 0x93, 0x26, 0xbb, 0x2a, 0xe2, 0xa5, 0x9d,
	0xf7, 0xe6, 0xbd, 0xe9, 0xcc, 0x2b, 0xec, 0xb6, 0x42, 0xeb, 0xbb, 0x47, 0x51, 0xf5, 0x83, 0x32,
	0x8a, 0x4e, 0xc6, 0x57, 0x53, 0x7e, 0xc4, 0x00, 0x57, 0xbe, 0xc3, 0xc5, 0x33, 0x3d, 0x02, 0x12,
	0x90, 0x66, 0xd1, 0x7e, 0xb2, 0x98, 0x2d, 0x0b, 0x6f, 0x68, 0xaa, 0x6f, 0xd5, 0xb6, 0x24, 0x61,
	0xa6, 0x2e, 0x3e, 0x23, 0xc0, 0x81, 0xa5, 0x19, 0xc4, 0xf5, 0xda, 0xba, 0xa3, 0x45, 0xc2, 0x63,
	0xb9, 0xa6, 0x14, 0xd0, 0xf9, 0xa0, 0x5a, 0x16, 0x8f, 0x0c, 0x7a, 0xb0, 0xb5, 0xd3, 0xac, 0x14,
	0x4b, 0xbc, 0xc6, 0xae, 0xc3, 0x00, 0x9f, 0xaa, 0xce, 0x88, 0xce, 0x30, 0x64, 0xc9, 0x29, 0xc7,
	0x8d, 0x87, 0xf4, 0x04, 0xd0, 0xea, 0xad, 0x17, 0x2c, 0xb5, 0x74, 0xb6, 0x9c, 0xff, 0xbf, 0x4d,
	0x15, 0x06, 0x38, 0x35, 0x47, 0xc6, 0x3e, 0xe9, 0x1c, 0xb2, 0x5a, 0x5f, 0x0c, 0xea, 0xa5, 0x0f,
	0x1a, 0x36, 0xb1, 0x53, 0x08, 0xcf, 0xe4, 0x2f, 0xb6, 0x3c, 0x86, 0xd9, 0x0f, 0x33, 0x25, 0xf6,
	0x93, 0xe2, 0xd5, 0xe4, 0x3b, 0x14, 0x43, 0x72, 0x23, 0x9b, 0x3c, 0xa2, 0x33, 0xc0, 0x67, 0xad,
	0x32, 0x52, 0x75, 0x79, 0x4c, 0xa7, 0x90, 0xde, 0x2a, 0xd9, 0x88, 0x3c, 0x29, 0xdf, 0x23, 0x98,
	0x5e, 0x77, 0x4f, 0xb2, 0x1b, 0xd3, 0x3b, 0x80, 0xb4, 0x36, 0xa2, 0xdd, 0x44, 0xb7, 0xb7, 0x59,
	0x76, 0xab, 0xa8, 0x5c, 0x9b, 0xa7, 0xd2, 0x89, 0x8a, 0x4b, 0x40, 0x0e, 0xfe, 0xc9, 0xab, 0x00,
	0x52, 0x6b, 0x6f, 0x19, 0x33, 0x23, 0x9c, 0xc8, 0x80, 0x5d, 0x4e, 0xe1, 0xa2, 0x31, 0x3c, 0xc2,
	0x71, 0x38, 0xe5, 0xde, 0xff, 0xd0, 0xc3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x83, 0x5d,
	0xbf, 0xe8, 0x01, 0x00, 0x00,
}
