// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	GenerateReq
	GenerateRsp
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateReq_IdType int32

const (
	GenerateReq_User         GenerateReq_IdType = 0
	GenerateReq_Group        GenerateReq_IdType = 1
	GenerateReq_UserMessage  GenerateReq_IdType = 2
	GenerateReq_GroupMessage GenerateReq_IdType = 3
)

var GenerateReq_IdType_name = map[int32]string{
	0: "User",
	1: "Group",
	2: "UserMessage",
	3: "GroupMessage",
}
var GenerateReq_IdType_value = map[string]int32{
	"User":         0,
	"Group":        1,
	"UserMessage":  2,
	"GroupMessage": 3,
}

func (x GenerateReq_IdType) String() string {
	return proto.EnumName(GenerateReq_IdType_name, int32(x))
}
func (GenerateReq_IdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type GenerateReq struct {
	Type GenerateReq_IdType `protobuf:"varint,1,opt,name=Type,json=type,enum=service.GenerateReq_IdType" json:"Type,omitempty"`
}

func (m *GenerateReq) Reset()                    { *m = GenerateReq{} }
func (m *GenerateReq) String() string            { return proto.CompactTextString(m) }
func (*GenerateReq) ProtoMessage()               {}
func (*GenerateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GenerateRsp struct {
	Id int64 `protobuf:"varint,1,opt,name=Id,json=id" json:"Id,omitempty"`
}

func (m *GenerateRsp) Reset()                    { *m = GenerateRsp{} }
func (m *GenerateRsp) String() string            { return proto.CompactTextString(m) }
func (*GenerateRsp) ProtoMessage()               {}
func (*GenerateRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*GenerateReq)(nil), "service.GenerateReq")
	proto.RegisterType((*GenerateRsp)(nil), "service.GenerateRsp")
	proto.RegisterEnum("service.GenerateReq_IdType", GenerateReq_IdType_name, GenerateReq_IdType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for IdService service

type IdServiceClient interface {
	Generate(ctx context.Context, in *GenerateReq, opts ...grpc.CallOption) (*GenerateRsp, error)
}

type idServiceClient struct {
	cc *grpc.ClientConn
}

func NewIdServiceClient(cc *grpc.ClientConn) IdServiceClient {
	return &idServiceClient{cc}
}

func (c *idServiceClient) Generate(ctx context.Context, in *GenerateReq, opts ...grpc.CallOption) (*GenerateRsp, error) {
	out := new(GenerateRsp)
	err := grpc.Invoke(ctx, "/service.IdService/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IdService service

type IdServiceServer interface {
	Generate(context.Context, *GenerateReq) (*GenerateRsp, error)
}

func RegisterIdServiceServer(s *grpc.Server, srv IdServiceServer) {
	s.RegisterService(&_IdService_serviceDesc, srv)
}

func _IdService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.IdService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdServiceServer).Generate(ctx, req.(*GenerateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.IdService",
	HandlerType: (*IdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _IdService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x1a, 0x18,
	0xb9, 0xb8, 0xdd, 0x53, 0xf3, 0x52, 0x8b, 0x12, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x85, 0xf4, 0xb9,
	0x58, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xa4, 0xf5, 0x60, 0xda,
	0x90, 0xd4, 0xe8, 0x79, 0xa6, 0x80, 0x94, 0x04, 0xb1, 0x94, 0x00, 0x49, 0x25, 0x07, 0x2e, 0x36,
	0x08, 0x5f, 0x88, 0x83, 0x8b, 0x25, 0x14, 0xa8, 0x5c, 0x80, 0x41, 0x88, 0x93, 0x8b, 0xd5, 0xbd,
	0x28, 0xbf, 0xb4, 0x40, 0x80, 0x51, 0x88, 0x9f, 0x8b, 0x1b, 0x24, 0xe8, 0x9b, 0x5a, 0x5c, 0x9c,
	0x98, 0x9e, 0x2a, 0xc0, 0x24, 0x24, 0xc0, 0xc5, 0x03, 0x96, 0x83, 0x89, 0x30, 0x2b, 0xc9, 0x22,
	0xb9, 0xa0, 0xb8, 0x40, 0x88, 0x8f, 0x8b, 0xc9, 0x33, 0x05, 0x6c, 0x3f, 0x73, 0x10, 0x53, 0x66,
	0x8a, 0x91, 0x2b, 0x17, 0xa7, 0x67, 0x4a, 0x30, 0xc4, 0x19, 0x42, 0x16, 0x5c, 0x1c, 0x30, 0xb5,
	0x42, 0x22, 0xd8, 0x1c, 0x27, 0x85, 0x45, 0xb4, 0xb8, 0x40, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x71,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x79, 0xed, 0xd9, 0x09, 0x01, 0x00, 0x00,
}
