// Code generated by protoc-gen-go.
// source: router.proto
// DO NOT EDIT!

/*
Package router is a generated protocol buffer package.

It is generated from these files:
	router.proto

It has these top-level messages:
	GroupUpReq
	MessageInReq
*/
package router

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import baseproto "github.com/longchat/longChat-Server/common/baseproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GroupUpReq struct {
	GroupId    int64  `protobuf:"varint,1,opt,name=GroupId,json=groupId" json:"GroupId,omitempty"`
	ServerAddr string `protobuf:"bytes,2,opt,name=ServerAddr,json=serverAddr" json:"ServerAddr,omitempty"`
}

func (m *GroupUpReq) Reset()                    { *m = GroupUpReq{} }
func (m *GroupUpReq) String() string            { return proto.CompactTextString(m) }
func (*GroupUpReq) ProtoMessage()               {}
func (*GroupUpReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MessageInReq struct {
	From    int64  `protobuf:"varint,1,opt,name=From,json=from" json:"From,omitempty"`
	To      int64  `protobuf:"varint,2,opt,name=To,json=to" json:"To,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=Content,json=content" json:"Content,omitempty"`
	Type    string `protobuf:"bytes,4,opt,name=Type,json=type" json:"Type,omitempty"`
	GroupId int64  `protobuf:"varint,5,opt,name=GroupId,json=groupId" json:"GroupId,omitempty"`
}

func (m *MessageInReq) Reset()                    { *m = MessageInReq{} }
func (m *MessageInReq) String() string            { return proto.CompactTextString(m) }
func (*MessageInReq) ProtoMessage()               {}
func (*MessageInReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*GroupUpReq)(nil), "router.GroupUpReq")
	proto.RegisterType((*MessageInReq)(nil), "router.MessageInReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Router service

type RouterClient interface {
	GroupUp(ctx context.Context, in *GroupUpReq, opts ...grpc.CallOption) (*baseproto.BaseRsp, error)
	MessageIn(ctx context.Context, in *MessageInReq, opts ...grpc.CallOption) (*baseproto.BaseRsp, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) GroupUp(ctx context.Context, in *GroupUpReq, opts ...grpc.CallOption) (*baseproto.BaseRsp, error) {
	out := new(baseproto.BaseRsp)
	err := grpc.Invoke(ctx, "/router.Router/GroupUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) MessageIn(ctx context.Context, in *MessageInReq, opts ...grpc.CallOption) (*baseproto.BaseRsp, error) {
	out := new(baseproto.BaseRsp)
	err := grpc.Invoke(ctx, "/router.Router/MessageIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Router service

type RouterServer interface {
	GroupUp(context.Context, *GroupUpReq) (*baseproto.BaseRsp, error)
	MessageIn(context.Context, *MessageInReq) (*baseproto.BaseRsp, error)
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_GroupUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GroupUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GroupUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GroupUp(ctx, req.(*GroupUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_MessageIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).MessageIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/MessageIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).MessageIn(ctx, req.(*MessageInReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "router.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GroupUp",
			Handler:    _Router_GroupUp_Handler,
		},
		{
			MethodName: "MessageIn",
			Handler:    _Router_MessageIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("router.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x69, 0x12, 0x12, 0xf5, 0x54, 0x31, 0x9c, 0x18, 0xac, 0x0e, 0x08, 0x65, 0x62, 0xc1,
	0x91, 0xe8, 0xc0, 0x88, 0xa0, 0x52, 0x51, 0x07, 0x16, 0xd3, 0x7e, 0x80, 0xfc, 0x31, 0x29, 0x12,
	0xb1, 0x8d, 0xed, 0x56, 0x82, 0x4f, 0x8f, 0x6b, 0x87, 0x10, 0xa4, 0x6e, 0xef, 0xdd, 0xf9, 0xfd,
	0x7c, 0x77, 0x30, 0xd3, 0x72, 0x6f, 0xb9, 0xa6, 0x4a, 0x4b, 0x2b, 0x31, 0x0d, 0x6e, 0xfe, 0xd0,
	0xbe, 0xdb, 0xdd, 0xbe, 0xa2, 0xb5, 0xec, 0x8a, 0x0f, 0x29, 0xda, 0x7a, 0x57, 0x5a, 0x2f, 0x96,
	0x4e, 0xdc, 0xbe, 0x72, 0x7d, 0xe0, 0xba, 0x70, 0xcd, 0x4e, 0x8a, 0xa2, 0x2a, 0x0d, 0xf7, 0x69,
	0xaf, 0x02, 0x28, 0x5f, 0x01, 0x3c, 0x3b, 0x96, 0xda, 0x2a, 0xc6, 0x3f, 0x91, 0x40, 0xe6, 0xdd,
	0xba, 0x21, 0x93, 0xeb, 0xc9, 0x4d, 0xcc, 0xb2, 0x36, 0x58, 0xbc, 0x02, 0x08, 0xb4, 0xc7, 0xa6,
	0xd1, 0x24, 0x72, 0xcd, 0x29, 0x03, 0x33, 0x54, 0xf2, 0x6f, 0x98, 0xbd, 0x70, 0x63, 0xca, 0x96,
	0xaf, 0xc5, 0x91, 0x84, 0x90, 0xac, 0xb4, 0xec, 0x7a, 0x4c, 0xf2, 0xe6, 0x34, 0x5e, 0x40, 0xb4,
	0x91, 0x3e, 0x1b, 0xb3, 0xc8, 0x2d, 0xe1, 0x7e, 0x5b, 0x4a, 0x61, 0xb9, 0xb0, 0x24, 0xf6, 0xc0,
	0xac, 0x0e, 0xf6, 0x98, 0xde, 0x7c, 0x29, 0x4e, 0x12, 0x5f, 0x4e, 0xac, 0xd3, 0xe3, 0xd9, 0xce,
	0xff, 0xcd, 0x76, 0x77, 0x80, 0x94, 0xf9, 0x73, 0xe0, 0xa2, 0x7f, 0xb3, 0x55, 0x88, 0xb4, 0x3f,
	0xd8, 0xdf, 0x7a, 0x73, 0xa4, 0xc3, 0x0d, 0xe8, 0x93, 0x53, 0xcc, 0xa8, 0xfc, 0x0c, 0xef, 0x61,
	0x3a, 0x8c, 0x8e, 0x97, 0xbf, 0xb1, 0xf1, 0x36, 0xa7, 0x83, 0x55, 0xea, 0x0b, 0x8b, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xde, 0x0e, 0xb0, 0x44, 0x9b, 0x01, 0x00, 0x00,
}
